### ISSUE TITLE
This API project is not authorized to use this API.

### ISSUE THREAD

**Issue by champjr** [sofyansitorus/WooCommerce-Shipping-Distance-Matrix#16]
Hi sir,

Maybe, I am doing something wrong but, the plugin seems to use its own api key set on a constant called "WCSDM_MAP_SECRET_KEY", which is decode in the main js file ( wcsdm.js ), to load and execute the google maps api script using the wrong api key rather than the one that I've set in the Api key field on the "Shipping Distance Matrix Settings" popup.

I've tested it on a brand new wp installation so that there is no conflict.

Thank you for your time.

Cheers!

**Comment by sofyansitorus** [comment]
@champjr Would you please elaborate more. Is the error printed in browse console? Is the map properly rendered in the wp-admin settings panel?

**Comment by sofyansitorus** [comment]
@champjr Wold you please include a screenshot. It will be be very helpful.

**Comment by champjr** [comment]
@sofyansitorus Yes with pleasure! 

You will find the screenshot below.

Steps to reproduce:

1. On the Wordpress plugins page, click on the 'settings' link below of your plugin.

2. Then, you will land on the Shipping Distance Matrix Settings popup.

3. Enter a newly generated google maps api key in the "API Key" field.

4. Try to search for an address in the map search field below the "API Key" field

5. An error will shows up in the console, saying "This API project is not authorized..."

6. Try to save the settings and re-try. Same error shows up in the browser console.

After digging in the code, I found that in the file `plugins/wcsdm/inlcudes/class-wcdm.php`, at line 256. A Constant named "WCSDM_MAP_SECRET_KEY" is outputted in the value attribute of an input with an id `map-secret-key`

```php
<input type="hidden" id="map-secret-key" value="<?php echo esc_attr( WCSDM_MAP_SECRET_KEY ); ?>">
```

The value is an encoded version of your google map api key.

Then in the file `plugins/wcsdm/assets/js/wcdm.js`, on the line 106, this encoded api key is decoded and used to make the request and is causing the error.

But I might be wrong.

Cheers!


```js
var mapScriptUrl = 'https://maps.googleapis.com/maps/api/js?key=' + self._decode($('#map-secret-key').val()) + '&libraries=geometry,places&&language=' + self._params.language;
$.getScript(mapScriptUrl, function () {
	self._buildGoogleMaps();
});
```
The problem is that the request doesn't use my api key but the one in the constant `WCSDM_MAP_SECRET_KEY`.


![This API project is not authorized](https://user-images.githubusercontent.com/6294104/39388716-3ab06300-4a50-11e8-9de8-bcefb15a8dab.png)

**Comment by sofyansitorus** [comment]
@champjr Yeah this is bug. Thanks for reporting it.
