### ISSUE TITLE
get_destination_info don't use customer address field

### ISSUE THREAD

**Issue by lightglitch** [sofyansitorus/WooCommerce-Shipping-Distance-Matrix#21]
Hi,

I activated the address field for calculated shipping using the filter **filter_woocommerce_shipping_calculator_enable_address** but still wasn't used.
After some debug the problem is that the **$fields_default** doesn't have any field with the name **address** but with the name **address_1**, so I had to fix using:

```
$field_data = isset( $fields_default[ $field ] ) ? $fields_default[ $field ] : false;
if ($field == 'address') {
    $field_data = isset( $fields_default[ 'address_1' ] ) ? $fields_default[ 'address_1' ] : false;				
}
if ( empty( $field_data ) ) {
    continue;
}
```

**Comment by siksmsi** [comment]
Do you have an idea, when the next update is planned, which solves this problem?

**Comment by sofyansitorus** [comment]
@siksmsi Probably will release major update  within next 2 - 3 weeks which will include this fix.

**Comment by siksmsi** [comment]
Thank you. That would be great.



Am Mo., 29. Okt. 2018 um 21:31 Uhr schrieb Sofyan Sitorus <
notifications@github.com>:

**Comment by dotsam** [comment]
I've also created the following workaround that spoofs the address_1 field as the address field, and then removes it before it's used anywhere else:
```
add_filter('woocommerce_default_address_fields', function($address_fields) {
  $address_fields['address'] = $address_fields['address_1'];

  return $address_fields;
});

function remove_extra_address_field($address_fields) {
  unset($address_fields['address']);
  unset($address_fields['billing_address']);
  unset($address_fields['shipping_address']);

  return $address_fields;
}
add_filter('woocommerce_billing_fields', 'remove_extra_address_field');
add_filter('woocommerce_shipping_fields', 'remove_extra_address_field');
add_filter('woocommerce_get_country_locale_default', 'remove_extra_address_field');
```

**Comment by siksmsi** [comment]
Thank you for your info. But I don't get it to run. 

I have the problem, that the distance calculation in cart and checkout only uses the city and country data. The Street would not be used. So I get a wrong distance value. 

The second problem is, that I often can not change the shipping method, after calculate the distance in cart or checkout. I can not find any reason, why the distance shipping method is hidden.
