### ISSUE TITLE
Use different API keys for admin map than Distance Matrix API

### ISSUE THREAD

**Issue by dotsam** [sofyansitorus/WooCommerce-Shipping-Distance-Matrix#22]
The plugin currently loads the frontend maps Javascript API based on the API key that's entered into the configuration screen. This API key is also used to make server-side requests to the Distance Matrix API.

My issue is that I would like to restrict the API keys I have generated for just my usage, but Google does not allow you to specify both an HTTP referrer restriction (for the admin map usage) and an IP address restriction (for the server-side distance matrix calculation), and therefore it's not possible to use one API key for both purposes if one wishes to restrict it.

Would it be possible to add two filters to set an API key for the javascript maps API and the distance matrix API? Then there wouldn't be a need to set them more than if multiple instances of the plugin are used, and in my use case, would allow me to set them in the filter via an ENV variable.

Thanks,
Sam

**Comment by sofyansitorus** [comment]
@dotsam For the API Key used by the settings form, it is not possible to add filter to manipulate the data as it validated realtime on input change. But I think it was a awesome idea to add filter to manipulate the API Key value before calling the Distance matrix API. I will add this in the next update.

**Comment by dotsam** [comment]
My thought was to inject a javascript variable with the key into the page, and if that's present, use it to load the maps javascript API instead of pulling the value from the field.

**Comment by sofyansitorus** [comment]
@dotsam I decided to improve the admin settings form, to enable to different API Key settings fields.
