### ISSUE TITLE
YITH WooCommerce Delivery Date Integration

### ISSUE THREAD

**Issue by lightglitch** [sofyansitorus/WooCommerce-Shipping-Distance-Matrix#48]
We are using this plugin the "YITH WooCommerce Delivery Date" and the YITH adds two new fields to the latest table that is being hidden in your case.

![inline-1016487138](https://user-images.githubusercontent.com/196953/52575106-8ad64580-2e15-11e9-8d58-cd42f87a088b.png)

We had to edit the css to be able to edit the fields.

**Comment by sofyansitorus** [comment]
@ lightglitch Unfortunately we do not have access to the plugin you mentioned as it was a premium plugin.

**Comment by sofyansitorus** [comment]
@lightglitch After checking deeper, I found the solution that just needs to add an extra setting group for third-party setting fields. Your issue should be covered in this commit https://github.com/sofyansitorus/WooCommerce-Shipping-Distance-Matrix/commit/f5a7f45b303512646552c9008be6b3bcda82c93c that bumped in version 2.1.1
